"""Initial migration

Revision ID: f4f9ea5a8e29
Revises: 
Create Date: 2026-01-10 10:31:08.667363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f9ea5a8e29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name_paternal', sa.VARCHAR(), nullable=False),
    sa.Column('last_name_maternal', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('role_name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name_paternal', sa.VARCHAR(), nullable=False),
    sa.Column('last_name_maternal', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('medical_conditions', sa.TEXT(), nullable=True),
    sa.Column('assigned_coach_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_nutri_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_nutri_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    
    op.create_table('planes_nutricionales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('nutricionista_id', sa.INTEGER(), nullable=True),
    sa.Column('genero', sa.INTEGER(), nullable=False),
    sa.Column('edad', sa.INTEGER(), nullable=False),
    sa.Column('peso', sa.FLOAT(), nullable=False),
    sa.Column('talla', sa.FLOAT(), nullable=False),
    sa.Column('nivel_actividad', sa.FLOAT(), nullable=False),
    sa.Column('objetivo', sa.VARCHAR(), nullable=False),
    sa.Column('es_contingencia_ia', sa.BOOLEAN(), nullable=True),
    sa.Column('calorias_ia_base', sa.FLOAT(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_nutricionales_id'), 'planes_nutricionales', ['id'], unique=False)
    
    op.create_table('planes_diarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('dia_numero', sa.INTEGER(), nullable=False),
    sa.Column('calorias_dia', sa.FLOAT(), nullable=False),
    sa.Column('proteinas_g', sa.FLOAT(), nullable=False),
    sa.Column('carbohidratos_g', sa.FLOAT(), nullable=False),
    sa.Column('grasas_g', sa.FLOAT(), nullable=False),
    sa.Column('sugerencia_entrenamiento_ia', sa.VARCHAR(), nullable=True),
    sa.Column('nota_asistente_ia', sa.VARCHAR(), nullable=True),
    sa.Column('validado_nutri', sa.BOOLEAN(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_nutricionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_diarios_id'), 'planes_diarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planes_diarios_id'), table_name='planes_diarios')
    op.drop_table('planes_diarios')
    op.drop_index(op.f('ix_planes_nutricionales_id'), table_name='planes_nutricionales')
    op.drop_table('planes_nutricionales')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###